import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

export default function Dashboard() {
  const [stats, setStats] = useState({
      totalDrivers: 0,
          approvedDrivers: 0,
              suspendedDrivers: 0,
                  activeTrips: 0,
                    });

                      async function loadStats() {
                          // TOTAL DRIVERS
                              const { count: totalDrivers } =
                                    await supabase
                                            .from("drivers")
                                                    .select("*", {
                                                              count: "exact",
                                                                        head: true,
                                                                                });

                                                                                    // APPROVED DRIVERS
                                                                                        const { count: approvedDrivers } =
                                                                                              await supabase
                                                                                                      .from("drivers")
                                                                                                              .select("*", {
                                                                                                                        count: "exact",
                                                                                                                                  head: true,
                                                                                                                                          })
                                                                                                                                                  .eq("status", "approved");

                                                                                                                                                      // SUSPENDED DRIVERS
                                                                                                                                                          const { count: suspendedDrivers } =
                                                                                                                                                                await supabase
                                                                                                                                                                        .from("drivers")
                                                                                                                                                                                .select("*", {
                                                                                                                                                                                          count: "exact",
                                                                                                                                                                                                    head: true,
                                                                                                                                                                                                            })
                                                                                                                                                                                                                    .eq("status", "suspended");

                                                                                                                                                                                                                        // ACTIVE TRIPS
                                                                                                                                                                                                                            const { count: activeTrips } =
                                                                                                                                                                                                                                  await supabase
                                                                                                                                                                                                                                          .from("trips")
                                                                                                                                                                                                                                                  .select("*", {
                                                                                                                                                                                                                                                            count: "exact",
                                                                                                                                                                                                                                                                      head: true,
                                                                                                                                                                                                                                                                              })
                                                                                                                                                                                                                                                                                      .eq("status", "active");

                                                                                                                                                                                                                                                                                          setStats({
                                                                                                                                                                                                                                                                                                totalDrivers:
                                                                                                                                                                                                                                                                                                        totalDrivers || 0,
                                                                                                                                                                                                                                                                                                              approvedDrivers:
                                                                                                                                                                                                                                                                                                                      approvedDrivers || 0,
                                                                                                                                                                                                                                                                                                                            suspendedDrivers:
                                                                                                                                                                                                                                                                                                                                    suspendedDrivers || 0,
                                                                                                                                                                                                                                                                                                                                          activeTrips: activeTrips || 0,
                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                      loadStats();

                                                                                                                                                                                                                                                                                                                                                          // REALTIME REFRESH
                                                                                                                                                                                                                                                                                                                                                              const channel = supabase
                                                                                                                                                                                                                                                                                                                                                                    .channel("dashboard-live")
                                                                                                                                                                                                                                                                                                                                                                          .on(
                                                                                                                                                                                                                                                                                                                                                                                  "postgres_changes",
                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                    event: "*",
                                                                                                                                                                                                                                                                                                                                                                                                              schema: "public",
                                                                                                                                                                                                                                                                                                                                                                                                                        table: "drivers",
                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                        () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  loadStats();
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .subscribe();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                supabase.removeChannel(channel);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2>📊 SchoolRide Analytics</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          display: "grid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gridTemplateColumns:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "repeat(auto-fit, minmax(220px, 1fr))",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          gap: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* TOTAL DRIVERS */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={cardStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>👨‍✈️ Total Drivers</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {stats.totalDrivers}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* APPROVED */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={cardStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>✅ Approved</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      stats.approvedDrivers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* SUSPENDED */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={cardStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>⛔ Suspended</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    stats.suspendedDrivers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* ACTIVE TRIPS */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={cardStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>🚍 Active Trips</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {stats.activeTrips}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // CARD STYLE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const cardStyle = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "#f5f5f5",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          boxShadow:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "0 2px 5px rgba(0,0,0,0.1)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };