import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

export default function Drivers() {
  const [drivers, setDrivers] = useState([]);
    const [loading, setLoading] = useState(true);

      // FETCH DRIVERS
        async function fetchDrivers() {
            setLoading(true);

                const { data, error } = await supabase
                      .from("drivers")
                            .select("*")
                                  .order("created_at", { ascending: false });

                                      if (error) {
                                            console.error(error);
                                                } else {
                                                      setDrivers(data);
                                                          }

                                                              setLoading(false);
                                                                }

                                                                  useEffect(() => {
                                                                      fetchDrivers();
                                                                        }, []);

                                                                          // UPDATE DRIVER STATUS
                                                                            async function updateStatus(id, status) {
                                                                                const { error } = await supabase
                                                                                      .from("drivers")
                                                                                            .update({ status })
                                                                                                  .eq("id", id);

                                                                                                      if (!error) {
                                                                                                            fetchDrivers();
                                                                                                                }
                                                                                                                  }

                                                                                                                    return (
                                                                                                                        <div>
                                                                                                                              <h2>👨‍✈️ Drivers Management</h2>

                                                                                                                                    <button onClick={fetchDrivers}>
                                                                                                                                            🔄 Refresh
                                                                                                                                                  </button>

                                                                                                                                                        {loading && <p>Loading drivers...</p>}

                                                                                                                                                              {!loading && drivers.length === 0 && (
                                                                                                                                                                      <p>No drivers found</p>
                                                                                                                                                                            )}

                                                                                                                                                                                  <div style={{ marginTop: 20 }}>
                                                                                                                                                                                          {drivers.map((d) => (
                                                                                                                                                                                                    <div
                                                                                                                                                                                                                key={d.id}
                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                          border: "1px solid #ccc",
                                                                                                                                                                                                                                                        padding: 10,
                                                                                                                                                                                                                                                                      marginBottom: 10,
                                                                                                                                                                                                                                                                                    borderRadius: 8,
                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                    <b>Name:</b> {d.name || "N/A"}
                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                          <b>Vehicle:</b>{" "}
                                                                                                                                                                                                                                                                                                                                                                                        {d.vehicle_type} -{" "}
                                                                                                                                                                                                                                                                                                                                                                                                      {d.vehicle_reg}
                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <b>Status:</b> {d.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <b>Verified:</b>{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {d.verified ? "Yes" : "No"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* ACTIONS */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ display: "flex", gap: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    updateStatus(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        d.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "approved"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Approve
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          updateStatus(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              d.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "rejected"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Reject
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                updateStatus(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    d.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "suspended"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Suspend
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }