import { useEffect, useState } from "react";
import { supabase } from "./lib/supabase";
import ParentTracking from "./pages/ParentTracking";
function Dashboard() {
  return <h2>📊 Dashboard</h2>;
  }

  function Drivers() {
    return <h2>👨‍✈️ Drivers</h2>;
    }

    function Trips() {
      return <h2>🚍 Trips</h2>;
      }

      function LiveMap() {
        return <h2>🗺️ Live Map</h2>;
        }

        export default function App() {
          // =====================
            // AUTH STATE
              // =====================
                const [session, setSession] = useState(null);

                  const [email, setEmail] = useState("");
                    const [password, setPassword] = useState("");

                      // =====================
                        // PAGE STATE
                          // =====================
                            const [page, setPage] = useState("dashboard");

                              // =====================
                                // SESSION LISTENER (UPGRADED)
                                  // =====================
                                    useEffect(() => {
                                        supabase.auth.getSession().then(({ data }) => {
                                              setSession(data.session);
                                                  });

                                                      const {
                                                            data: { subscription },
                                                                } = supabase.auth.onAuthStateChange(
                                                                      (_event, session) => {
                                                                              setSession(session);
                                                                                    }
                                                                                        );

                                                                                            return () => subscription.unsubscribe();
                                                                                              }, []);

                                                                                                // =====================
                                                                                                  // LOGIN
                                                                                                    // =====================
                                                                                                      async function login() {
                                                                                                          const { error } =
                                                                                                                await supabase.auth.signInWithPassword({
                                                                                                                        email,
                                                                                                                                password,
                                                                                                                                      });

                                                                                                                                          if (error) {
                                                                                                                                                alert(error.message);
                                                                                                                                                    }
                                                                                                                                                      }

                                                                                                                                                        // =====================
                                                                                                                                                          // LOGOUT
                                                                                                                                                            // =====================
                                                                                                                                                              async function logout() {
                                                                                                                                                                  await supabase.auth.signOut();
                                                                                                                                                                    }

                                                                                                                                                                      // =====================
                                                                                                                                                                        // LOGIN SCREEN
                                                                                                                                                                          // =====================
                                                                                                                                                                            if (!session) {
                                                                                                                                                                                return (
                                                                                                                                                                                      <div style={{ padding: 20 }}>
                                                                                                                                                                                              <h1>🔐 SchoolRide Login</h1>

                                                                                                                                                                                                      <input
                                                                                                                                                                                                                placeholder="Email"
                                                                                                                                                                                                                          value={email}
                                                                                                                                                                                                                                    onChange={(e) =>
                                                                                                                                                                                                                                                setEmail(e.target.value)
                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                          <br />
                                                                                                                                                                                                                                                                                  <br />

                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                              placeholder="Password"
                                                                                                                                                                                                                                                                                                                        value={password}
                                                                                                                                                                                                                                                                                                                                  onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                              setPassword(e.target.value)
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                        <br />
                                                                                                                                                                                                                                                                                                                                                                                <br />

                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={login}>
                                                                                                                                                                                                                                                                                                                                                                                                  Login
                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                        // =====================
                                                                                                                                                                                                                                                                                                                                                                                                                          // DASHBOARD UI
                                                                                                                                                                                                                                                                                                                                                                                                                            // =====================
                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ padding: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <h1>🚍 SchoolRide Admin</h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={logout}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      Logout
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <hr />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* NAVIGATION */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          gap: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flexWrap: "wrap",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setPage("dashboard")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Dashboard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setPage("drivers")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Drivers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setPage("trips")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Trips
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setPage("map")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Live Map
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <hr />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* PAGES */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {page === "dashboard" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Dashboard />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {page === "drivers" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Drivers />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {page === "trips" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Trips />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {page === "map" && <LiveMap />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }